image: docker:stable

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY/my_group/my_project:latest
  CONTAINER_TEST_IMAGE: $DOCKER_REGISTRY/my_group/my_project:$CI_COMMIT_REF_SLUG

before_script:
  - docker info
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker info
  - docker-compose --version
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY

stages:
- build
- test
- deploy

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - dev

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker-compose -f docker-compose.test.yml run web
  tags:
    - dev

deploy:
  stage: deploy
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker-compose down
    - docker-compose -p myapp up -d
  only:
    - master
  tags:
    - dev
