image: docker:stable

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY/my_group/my_project

before_script:
  - docker info
  - apk add --no-cache py-pip
  - pip install docker-compose
  - "echo Current location is: `pwd`"
  - docker info
  - docker-compose --version
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY

stages:
- build
- test
- deploy

build:
  stage: build
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE:latest
  tags:
    - dev

test:
  stage: test
  script:
    - docker-compose rm -f
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker-compose -f docker-compose.test.yml run web
  tags:
    - dev

deploy:
  stage: deploy
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker-compose down
    - docker-compose -p my_app up -d
  only:
    - master
  tags:
    - dev
