version: "3"

services:
  # Postgres
  postgres:
    restart: always
    image: postgres:latest
    ports:
    - 5432

  # App
  web:
    build: .
    environment:
    - DJANGO_SETTINGS_MODULE=config.settings_test
    - DATABASE_HOST=postgres
    - DATABASE_NAME=test
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=
    image: $CONTAINER_RELEASE_IMAGE:latest
    links:
    - postgres:postgres
    depends_on:
    - postgres

