version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
    - 5432
    volumes:
    - "/web/myapp-database:/var/lib/postgresql/data"

  web:
    restart: always
    env_file:
    - /conf/.env
    image: $CONTAINER_RELEASE_IMAGE
    links:
    - postgres:postgres
    ports:
    - "8000:8000"
    depends_on:
    - postgres
    volumes:
      - "/web/myapp-data:/data"
      - "/web/myapp-conf:/conf"