version: "3"

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
    - 5432

  web:
    build: .
    environment:
    - DJANGO_SETTINGS_MODULE=config.settings_test
    - DATABASE_HOST=postgres
    - DATABASE_NAME=postgres
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=
    image: $CONTAINER_TEST_IMAGE
    links:
    - postgres:postgres
    depends_on:
    - postgres
